apiVersion: apps/v1
kind: Deployment
metadata:
  name: slim-deploy
  labels:
    app: nccoffee
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nccoffee
  template:
    metadata:
      labels:
        app: nccoffee
    spec:
      containers:
      - name: nccoffee
        image: slim3116/3116test:web01
        imagePullPolicy: Always
        ports:
        - containerPort: 80